# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Just Known Lim
email: jklim1253@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Develope.. Design.. Do.. ....with Happiness
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jklim1253.github.io" # the base hostname & protocol for your site
github_username:  jklim1253

encoding: "utf-8"
markdown_ext: "markdown,md"

# Build settings
markdown: kramdown
highlighter: pygments

safe: true
lsi: false

##
permalink: none
