# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: 1253
email: jklim1253@gmail.com
description: osiobaro
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jklim1253

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Just-the-docs settings

# top left logo instead of title
#logo: "/assets/images/logo.png"

# search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# top right link
aux_links:
  "jklim1253 on Github":
    - "//github.com/jklim1253"
aux_links_new_tab: true

# heading anchor links
heading_anchors: true

# footer content
footer_content: "Copyright &copy; 2021-2022 jklim. Distributed by an <a href=\"https://github.com/jklim1253/jklim1253.github.io/tree/master/LICENSE.txt\">MIT license.</a>"
last_edit_timestamp: true
last_edit_time_format: "%F %a at %T %Z"
gh_edit_link: true
gh_edit_link_text: "페이지 수정"
gh_edit_repository: "https://github.com/jklim1253/jklim1253.github.com"
gh_edit_branch: "master"
gh_edit_source: publish
gh_edit_view_mode: "tree"

# color scheme
color_scheme: light

# google analytics
#ga_tracking: 
#ga_tracking_anonymize_ip: true

# Document collections
# collections:
#   posts:
#     permalink: "/:collection/:path/"
#     output: true
#   tutorials:
#     permalink: "/:collection/:path/"
#     output: true

# just_the_docs:
#   collections:
#     posts:
#       name: Post
#     tutorials:
#       name: Tutorial